### ISSUE TITLE
Migrate extension to the Camunda Community Hub?

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/email-incident-notification-plugin#6]
Hi Gerardo and the team at JIT,

I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/Camunda-Community-Hub/community)?

We'd also love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. If you are for any reason no longer able to maintain this extension, if it is migrated to the Hub I would be more than happy to add a lifecycle badge to it indicating that the project is in need of a new maintainer.

I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks.

Thank you so much for your time. I look forward to hearing from you.

Best,
Rin

**Comment by bassgelo** [comment]
Hi,


Sorry for the late reply. I am intermittently in the office due to some
personal plans in summer but thank you for reaching out.

We answer with yes and would like very much to migrate this project to
the Camunda
Community Hub <https://github.com/Camunda-Community-Hub/community>.


I would suggest we do the following:



   1. As per your recommendation, I would like to get the instructions on
   how to do it via email.
   2. Let us organize an online appointment. We would love to give you
   feedback.
   3. And in the same call, we would like to discuss the following point:
   including a similar project in the migration. We are Camunda Partners and
   are interested in increasing our activity inside the Camunda community. We
   have at the moment two public projects, namely:


https://github.com/jit-open/email-incident-notification-plugin

https://github.com/jit-open/CsvToDmnConverter


Do you have by any chance Calendly so that I can choose a time that suits
us both? Just head ups that in the following weeks I have holidays, and my
availability might not fit yours. We will manage to find an appointment.

And the last point, my company email is ***@***.***

I would be very grateful if you can write to me there.


I am looking forward to talking to you.


Best,

Gerardo

**Comment by celanthe** [comment]
Hi @bassgelo! Thank you so much for getting back to me. Per your request, I've sent you an email with my Calendly link. I look forward to connecting with you! :)

**Comment by celanthe** [comment]
Hi @bassgelo! I hope today finds you well! :) I just wanted to circle back on this. I look forward to connecting!

**Comment by bassgelo** [comment]
Hi,
Hope you are doing well.
Sorry for the late reply, I am back from holidays and my team had other
priorities in the meantime.
Next week we will do the migration, so thank you very much for the
information.
Could you please send me again the invitation to join your organization in
Github ? The link you sent me expired.

Thanks in advance
Gerardo

**Comment by celanthe** [comment]
Hi @bassgelo! Not to worry! :) I've sent you a new invite to join the Community Hub. We look forward to having this extension there, and truly appreciate your wonderful contributions to Camunda!
